### ISSUE TITLE
Won't work under Ubuntu 14.04

### ISSUE THREAD

**Issue by Quinchu** [Morgas01/XDCC-HQ#1]
This is the error I get from terminal:

./enshureFolder
fs.js:747
  return binding.mkdir(pathModule._makeLong(path),
                 ^
Error: ENOENT, no such file or directory ''
    at Error (native)
    at Object.fs.mkdirSync (fs.js:747:18)
    at module.exports (/home/core/Node/XDCC-HQ/webapp/Morgas/src/NodeJs/enshureFolder.js:12:7)
    at /home/core/Node/XDCC-HQ/logger.js:7:2
    at Object.<anonymous> (/home/core/Node/XDCC-HQ/logger.js:37:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

when I run node server.js

Any recommendations?

**Comment by BenjaminLawson** [comment]
I'm getting almost the same error on Mac OS X 10.10.4.

```
fs.js:642
  return binding.mkdir(pathModule._makeLong(path),
                 ^
Error: ENOENT, no such file or directory ''
    at Object.fs.mkdirSync (fs.js:642:18)
    at module.exports (.../XDCC-HQ/webapp/Morgas/src/NodeJs/enshureFolder.js:12:7)
    at .../XDCC-HQ/logger.js:7:2
    at Object.<anonymous> (.../XDCC-HQ/logger.js:37:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

EDIT: I noticed the module AXDCC says it only works on Windows on Linux. But it's interesting I'm getting the same error as Quinchu.

**Comment by Morgas01** [comment]
The whole project is still in its early phase so its a little fragile.
At the moment I'm developing on a windows machine so I don't know about 
compatibility problems.

But is seems the path is an empty string which is not a valid folder to 
create.
The path should be >> path.join(__dirname,"logs"); <<, in your case 
"/Users/Ben/Desktop/XDCC-HQ-master/logs".

HTH

Am 11.09.2015 um 23:15 schrieb JordekFluffball:

**Comment by Morgas01** [comment]
probably was an error with the leading / in unix absolute paths.
should be fixed now in submodule

**Comment by Quinchu** [comment]
With this newer package, I'm now getting another error.

``` javascript
module.js:489
    throw err;
          ^
SyntaxError: /home/core/Node/XDCC-HQ/config.json: Unexpected token c
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:486:27)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/core/Node/XDCC-HQ/libs/configManager.js:28:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

And Here is my Userconfig file

``` json
{
        "serverPort": 8080,
        "ircNick": "IRC_NICK",
        "downloadDir": "/home/username/Downloads",
        "maxDownloads": 8,
        "maxNetworkDownloads": 4,
        "maxBotDownloads": 2,
        "autoStartDownloads": false,
        "cleanNames": true,
        "checkCRC": true,
        "resolvedDownloadDir": "\\home\username\Downloads"
}
```

**Comment by Morgas01** [comment]
@Quinchu 
with that json file i get an:

```
SyntaxError: c:\dev\workspace\XDCC-HQ\config.json: Unexpected token s
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:460:27)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

seems like an escape error at "resolvedDownloadDir".

The "resolvedDownloadDir" is detected at runtime from cwd + downloadDir and shouldn't appear in the config.json as it will be overwritten anyway.

Furthermore the config.json is now only the default and the actualy used configuration will be written & loaded from ./temp/config.json as the first changes are made via the gui

**Comment by Quinchu** [comment]
``` javascript

could not load user config
{"name":"server","hostname":"Ubunty","pid":3344,"level":30,"msg":"starting server { on: [Function: addListener],\n  once: [Function: once],\n  addListener: [Function: addListener],\n  removeListener: [Function: removeListener],\n  emit: [Function: emit],\n  add: [Function],\n  save: [Function],\n  serverPort: 3000,\n  ircNick: 'IRC_NICK',\n  downloadDir: 'Downloads',\n  maxDownloads: 8,\n  maxNetworkDownloads: 4,\n  maxBotDownloads: 2,\n  autoStartDownloads: false,\n  cleanNames: true,\n  checkCRC: true,\n  resolvedDownloadDir: '/home/core/Node/XDCC-HQ/Downloads',\n  _events: {} }","time":"2015-09-22T22:05:41.475Z","v":0}
/home/core/Node/XDCC-HQ/webapp/rest/download.js:22
ponse.write("data: " + JSON.stringify(downloads.db.getValues().map(d=>d.fields
                                                                    ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/core/Node/XDCC-HQ/server.js:78:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

```

Sorry, it was in your config, pulled all the new information in and now I'm getting this.
I'm starting it by running 'node server.js' after pulling all npm installs for the XDCC-HQ folder and the Morgas folder. 

``` json
{
        "serverPort": 3000,
        "ircNick": "IRC_NICK",
        "downloadDir": "Downloads",
        "maxDownloads": 8,
        "maxNetworkDownloads": 4,
        "maxBotDownloads": 2,
        "autoStartDownloads": false,
        "cleanNames": true,
        "checkCRC": true
}
```

This is also my config file now. Haha, maybe I should just switch to Windows eh? ;)

**Comment by Morgas01** [comment]
@Quinchu 
Do you have node version 4? Lesser versions don't support arrow functions.
And my plan is to run this on a raspberry Raspberry Pi, so it should work on unix systems some time.

**Comment by Quinchu** [comment]
Well that seemed to be my problem. It's working on Ubuntu with the latest version of Nodejs.
